{
 "title": "bsbmp-exporter",
 "description": "Temperature, Humidity, and Pressure readings from Bosch Sensortec sensors.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "group", "label": "Group", "query": "label_values(bsbmp_group)" }
  ]
 },
 "panels": [
  {
   "title": "Average Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((bsbmp_temp_celsius{bsbmp_group=\"$group\"}*9/5)+32)/count(bsbmp_temp_celsius{bsbmp_group=\"$group\"})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "expr": "(bsbmp_temp_celsius{bsbmp_group=\"$group\"}*9/5)+32"
    }
   ]
  },
  {
   "title": "Average Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bsbmp_humidity_percent{bsbmp_group=\"$group\"})/count(bsbmp_humidity_percent{bsbmp_group=\"$group\"})"
    }
   ]
  },
  {
   "title": "Percent Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "bsbmp_humidity_percent{bsbmp_group=\"$group\"}"
    }
   ]
  },
  {
   "title": "Average Pressure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bsbmp_pressure_pascal{bsbmp_group=\"$group\"}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "yaxes": [
    { "format": "pressurepa" }
   ],
   "targets": [
    {
     "expr": "bsbmp_pressure_pascal{bsbmp_group=\"$group\"}"
    }
   ]
  }
 ]
}