kind: Endpoints
apiVersion: v1
metadata:
  name: bsbmp-exporter
  namespace: monitoring
subsets:
  - addresses:
      - ip: 192.168.1.77
    ports:
      - port: 9756
        name: http
        protocol: TCP
