kind: Service
apiVersion: v1
metadata:
  labels:
    app: bsbmp-exporter
    bsbmp_group: basement
  name: bsbmp-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9756
    targetPort: http
